language: 
  - node_js
node_js:
  - "lts/*"
cache:
  - npm
before_install:
  - cd client
script:
  - npm install wait-on -g
  - yarn start & wait-on http://localhost:3000
  - yarn build
deploy:
  provider: script
  script: bash client/ftp.sh
  on:
    branch: master