language: 
  - node_js
node_js:
  - "lts/*"
cache:
  - npm
before_install:
  - cd client
script:
  - npm install wait-on -g
  - yarn start & wait-on http://localhost:3000
  - yarn build
after_success:
  - cd build
  - "find * -type f -exec curl -u ${FTP_USER}\@kevin-delcourt.net:${FTP_PSWD} --ftp-create-dirs -T {} ftp.online.net/soundbox/{} \;"