language: 
  - node_js
node_js:
  - "lts/*"
cache:
  - npm
before_install:
  - cd client
  - bash ftp.sh
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: bash ftp.sh
  on:
    branch: master